In [6]:
pip install google-cloud-bigquery pandas pyarrow db-dtypes requests

Requirement already satisfied: google-cloud-bigquery in /opt/python/envs/default_3_11/lib/python3.11/site-packages (3.44.0)
Requirement already satisfied: pandas in /opt/python/envs/default_3_11/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: pyarrow in /opt/python/envs/default_3_11/lib/python3.11/site-packages (23.0.1)
Requirement already satisfied: db-dtypes in /opt/python/envs/default_3_11/lib/python3.11/site-packages (1.7.1)
Requirement already satisfied: requests in /opt/python/envs/default_3_11/lib/python3.11/site-packages (2.33.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.28.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (2.34.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.57.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (2.7.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (2.10.1)
Requirement already satisfied: packaging>=24.2.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (26.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (3.16)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (2026.5.20)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.75.1)
Requirement already satisfied: protobuf<8.0.0,>=6.33.5 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.26.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.28.3)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.83.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.83.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (50.0.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: typing-extensions~=4.12 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from grpcio<2.0.0,>=1.59.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: numpy>=1.23.2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pandas) (2.1.3)
Requirement already satisfied: pytz>=2020.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pandas) (2026.2)
Requirement already satisfied: cffi>=2.0.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.1.1)
Requirement already satisfied: pycparser in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import os

print("Project ID found:", bool(os.environ.get("gcl_project_id")))
print("GCP service account key found:", bool(os.environ.get("GCP_SA_KEY")))

Project ID found: True
GCP service account key found: True

In [8]:
import sys, json
import pandas as pd
from google.cloud import bigquery

PROJECT_ID = os.environ["gcl_project_id"]   # ← замінити на свій проєкт
LOCATION   = "EU"

creds = None

if "google.colab" in sys.modules:                  # Colab
    from google.colab import auth
    auth.authenticate_user()

elif os.environ.get("GCP_SA_KEY"):                 # Datalore: ключ у змінній середовища
    from google.oauth2 import service_account
    creds = service_account.Credentials.from_service_account_info(
        json.loads(os.environ["GCP_SA_KEY"]),
        scopes=["https://www.googleapis.com/auth/cloud-platform"])

client = bigquery.Client(project=PROJECT_ID, location=LOCATION, credentials=creds)
print("проєкт:", client.project)

проєкт: datalab-504011

In [9]:
# Завдання 3. Ноутбук 02 — вимір валют

# Завдання 3.1. Прочитайте з nbu_raw.raw_rates колонки ingested_at, business_date, payload

nbu_raw_rates_table = f"""
SELECT ingested_at, business_date, payload
FROM `{PROJECT_ID}.nbu_raw.raw_rates`
"""

raw_rates_df = client.query(nbu_raw_rates_table).to_dataframe()

raw_rates_df

# Завдання 3.2. Розгорніть JSON-текст із payload у колонки.

parsed = pd.json_normalize(raw_rates_df["payload"].map(json.loads))
parsed

# Завдання 3.3. Нормалізуйте значення: 

parsed["cc"] = parsed["cc"].str.strip().str.upper()
parsed["txt"] = parsed["txt"].str.strip()
parsed["r030"] = parsed["r030"].astype("Int64")
parsed

/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,cc,exchangedate,r030,rate,special,txt
0,DZD,25.08.2026,12,0.33615,None,Алжирський динар
1,AUD,25.08.2026,36,32.03210,None,Австралійський долар
2,BDT,25.08.2026,50,0.36460,None,Така
3,CAD,25.08.2026,124,32.29020,None,Канадський долар
4,CNY,25.08.2026,156,6.64940,None,Юань Женьміньбі
...,...,...,...,...,...,...
85,PLN,25.08.2026,985,12.10590,None,Злотий
86,XAU,25.08.2026,959,208220.86000,None,Золото
87,XAG,25.08.2026,961,3096.37000,None,Срібло
88,XPT,25.08.2026,962,84163.82000,None,Платина
89,XPD,25.08.2026,964,60381.49000,None,Паладій

In [10]:
raw_rates_df

,ingested_at,business_date,payload
0,2026-08-24 16:53:34.648229+00:00,2026-08-24,"{""cc"": ""DZD"", ""exchangedate"": ""25.08.2026"", ""r..."
1,2026-08-24 16:53:34.648247+00:00,2026-08-24,"{""cc"": ""AUD"", ""exchangedate"": ""25.08.2026"", ""r..."
2,2026-08-24 16:53:34.648259+00:00,2026-08-24,"{""cc"": ""BDT"", ""exchangedate"": ""25.08.2026"", ""r..."
3,2026-08-24 16:53:34.648270+00:00,2026-08-24,"{""cc"": ""CAD"", ""exchangedate"": ""25.08.2026"", ""r..."
4,2026-08-24 16:53:34.648280+00:00,2026-08-24,"{""cc"": ""CNY"", ""exchangedate"": ""25.08.2026"", ""r..."
...,...,...,...
85,2026-08-24 18:28:24.698806+00:00,2026-08-24,"{""cc"": ""PLN"", ""exchangedate"": ""25.08.2026"", ""r..."
86,2026-08-24 18:28:24.698822+00:00,2026-08-24,"{""cc"": ""XAU"", ""exchangedate"": ""25.08.2026"", ""r..."
87,2026-08-24 18:28:24.698837+00:00,2026-08-24,"{""cc"": ""XAG"", ""exchangedate"": ""25.08.2026"", ""r..."
88,2026-08-24 18:28:24.698854+00:00,2026-08-24,"{""cc"": ""XPT"", ""exchangedate"": ""25.08.2026"", ""r..."
89,2026-08-24 18:28:24.698868+00:00,2026-08-24,"{""cc"": ""XPD"", ""exchangedate"": ""25.08.2026"", ""r..."

In [11]:
# Завдання 3.4. Залиште по одному рядку на валюту, узявши найсвіжіший запис за ingested_at

parsed["ingested_at"] = raw_rates_df["ingested_at"].values
parsed["business_date"] = raw_rates_df["business_date"].values

dim = (parsed.sort_values("ingested_at")
          .drop_duplicates(subset="cc", keep="last")).reset_index(drop=True)


dim = dim.rename(columns={
    "cc": "currency_code",
    "txt": "currency_name"
})

dim

,currency_code,exchangedate,r030,rate,special,currency_name,ingested_at,business_date
0,DZD,25.08.2026,12,0.336150,None,Алжирський динар,2026-08-24 18:28:24.698111,2026-08-24
1,AUD,25.08.2026,36,32.032100,None,Австралійський долар,2026-08-24 18:28:24.698141,2026-08-24
2,BDT,25.08.2026,50,0.364600,None,Така,2026-08-24 18:28:24.698161,2026-08-24
3,CAD,25.08.2026,124,32.290200,None,Канадський долар,2026-08-24 18:28:24.698178,2026-08-24
4,CNY,25.08.2026,156,6.649400,None,Юань Женьміньбі,2026-08-24 18:28:24.698193,2026-08-24
5,CZK,25.08.2026,203,2.164300,None,Чеська крона,2026-08-24 18:28:24.698210,2026-08-24
6,DKK,25.08.2026,208,6.977200,None,Данська крона,2026-08-24 18:28:24.698227,2026-08-24
7,HKD,25.08.2026,344,5.704700,None,Гонконгівський долар,2026-08-24 18:28:24.698249,2026-08-24
8,HUF,25.08.2026,348,0.143956,None,Форинт,2026-08-24 18:28:24.698268,2026-08-24
9,INR,25.08.2026,356,0.466920,None,Індійська рупія,2026-08-24 18:28:24.698283,2026-08-24
10,IDR,25.08.2026,360,0.002523,None,Рупія,2026-08-24 18:28:24.698299,2026-08-24
11,ILS,25.08.2026,376,14.949000,None,Новий ізраїльський шекель,2026-08-24 18:28:24.698317,2026-08-24
12,JPY,25.08.2026,392,0.281050,None,Єна,2026-08-24 18:28:24.698334,2026-08-24
13,KZT,25.08.2026,398,0.097790,None,Теньге,2026-08-24 18:28:24.698352,2026-08-24
14,KRW,25.08.2026,410,0.032310,None,Вона,2026-08-24 18:28:24.698369,2026-08-24
15,LBP,25.08.2026,422,0.000499,None,Ліванський фунт,2026-08-24 18:28:24.698402,2026-08-24
16,MYR,25.08.2026,458,11.058100,None,Малайзійський ринггіт,2026-08-24 18:28:24.698420,2026-08-24
17,MXN,25.08.2026,484,2.641000,None,Мексиканське песо,2026-08-24 18:28:24.698442,2026-08-24
18,MDL,25.08.2026,498,2.603000,None,Молдовський лей,2026-08-24 18:28:24.698457,2026-08-24
19,NZD,25.08.2026,554,26.661600,None,Новозеландський долар,2026-08-24 18:28:24.698473,2026-08-24
20,NOK,25.08.2026,578,4.801000,None,Норвезька крона,2026-08-24 18:28:24.698488,2026-08-24
21,SAR,25.08.2026,682,11.906600,None,Саудівський ріял,2026-08-24 18:28:24.698501,2026-08-24
22,SGD,25.08.2026,702,35.195500,None,Сінгапурський долар,2026-08-24 18:28:24.698516,2026-08-24
23,VND,25.08.2026,704,0.001709,None,Донг,2026-08-24 18:28:24.698530,2026-08-24
24,ZAR,25.08.2026,710,2.795000,None,Ренд,2026-08-24 18:28:24.698544,2026-08-24
25,SEK,25.08.2026,752,4.707200,None,Шведська крона,2026-08-24 18:28:24.698559,2026-08-24
26,CHF,25.08.2026,756,55.738100,None,Швейцарський франк,2026-08-24 18:28:24.698591,2026-08-24
27,THB,25.08.2026,764,1.368050,None,Бат,2026-08-24 18:28:24.698608,2026-08-24
28,AED,25.08.2026,784,12.171600,None,Дирхам ОАЕ,2026-08-24 18:28:24.698622,2026-08-24
29,TND,25.08.2026,788,15.388800,None,Туніський динар,2026-08-24 18:28:24.698637,2026-08-24
30,EGP,25.08.2026,818,0.879700,None,Єгипетський фунт,2026-08-24 18:28:24.698650,2026-08-24
31,GBP,25.08.2026,826,60.974200,None,Фунт стерлінгів,2026-08-24 18:28:24.698664,2026-08-24
32,USD,25.08.2026,840,44.706400,N,Долар США,2026-08-24 18:28:24.698679,2026-08-24
33,RSD,25.08.2026,941,0.444550,None,Сербський динар,2026-08-24 18:28:24.698693,2026-08-24
34,AZN,25.08.2026,944,26.299400,None,Азербайджанський манат,2026-08-24 18:28:24.698707,2026-08-24
35,RON,25.08.2026,946,9.934300,None,Румунський лей,2026-08-24 18:28:24.698721,2026-08-24
36,TRY,25.08.2026,949,0.929800,None,Турецька ліра,2026-08-24 18:28:24.698744,2026-08-24
37,XDR,25.08.2026,960,61.364100,None,СПЗ (спеціальні права запозичення),2026-08-24 18:28:24.698761,2026-08-24
38,EUR,25.08.2026,978,52.159400,None,Євро,2026-08-24 18:28:24.698777,2026-08-24
39,GEL,25.08.2026,981,17.130500,None,Ларі,2026-08-24 18:28:24.698792,2026-08-24
40,PLN,25.08.2026,985,12.105900,None,Злотий,2026-08-24 18:28:24.698806,2026-08-24
41,XAU,25.08.2026,959,208220.860000,None,Золото,2026-08-24 18:28:24.698822,2026-08-24
42,XAG,25.08.2026,961,3096.370000,None,Срібло,2026-08-24 18:28:24.698837,2026-08-24
43,XPT,25.08.2026,962,84163.820000,None,Платина,2026-08-24 18:28:24.698854,2026-08-24
44,XPD,25.08.2026,964,60381.490000,None,Паладій,2026-08-24 18:28:24.698868,2026-08-24

In [12]:
# Завдання 3.5. Відсортуйте за currency_code і додайте першою колонкою сурогатний ключ currency_key — послідовні числа від 1.

dim.insert(0, "currency_key", range(1, len(dim) +1))

dim

,currency_key,currency_code,exchangedate,r030,rate,special,currency_name,ingested_at,business_date
0,1,DZD,25.08.2026,12,0.336150,None,Алжирський динар,2026-08-24 18:28:24.698111,2026-08-24
1,2,AUD,25.08.2026,36,32.032100,None,Австралійський долар,2026-08-24 18:28:24.698141,2026-08-24
2,3,BDT,25.08.2026,50,0.364600,None,Така,2026-08-24 18:28:24.698161,2026-08-24
3,4,CAD,25.08.2026,124,32.290200,None,Канадський долар,2026-08-24 18:28:24.698178,2026-08-24
4,5,CNY,25.08.2026,156,6.649400,None,Юань Женьміньбі,2026-08-24 18:28:24.698193,2026-08-24
5,6,CZK,25.08.2026,203,2.164300,None,Чеська крона,2026-08-24 18:28:24.698210,2026-08-24
6,7,DKK,25.08.2026,208,6.977200,None,Данська крона,2026-08-24 18:28:24.698227,2026-08-24
7,8,HKD,25.08.2026,344,5.704700,None,Гонконгівський долар,2026-08-24 18:28:24.698249,2026-08-24
8,9,HUF,25.08.2026,348,0.143956,None,Форинт,2026-08-24 18:28:24.698268,2026-08-24
9,10,INR,25.08.2026,356,0.466920,None,Індійська рупія,2026-08-24 18:28:24.698283,2026-08-24
10,11,IDR,25.08.2026,360,0.002523,None,Рупія,2026-08-24 18:28:24.698299,2026-08-24
11,12,ILS,25.08.2026,376,14.949000,None,Новий ізраїльський шекель,2026-08-24 18:28:24.698317,2026-08-24
12,13,JPY,25.08.2026,392,0.281050,None,Єна,2026-08-24 18:28:24.698334,2026-08-24
13,14,KZT,25.08.2026,398,0.097790,None,Теньге,2026-08-24 18:28:24.698352,2026-08-24
14,15,KRW,25.08.2026,410,0.032310,None,Вона,2026-08-24 18:28:24.698369,2026-08-24
15,16,LBP,25.08.2026,422,0.000499,None,Ліванський фунт,2026-08-24 18:28:24.698402,2026-08-24
16,17,MYR,25.08.2026,458,11.058100,None,Малайзійський ринггіт,2026-08-24 18:28:24.698420,2026-08-24
17,18,MXN,25.08.2026,484,2.641000,None,Мексиканське песо,2026-08-24 18:28:24.698442,2026-08-24
18,19,MDL,25.08.2026,498,2.603000,None,Молдовський лей,2026-08-24 18:28:24.698457,2026-08-24
19,20,NZD,25.08.2026,554,26.661600,None,Новозеландський долар,2026-08-24 18:28:24.698473,2026-08-24
20,21,NOK,25.08.2026,578,4.801000,None,Норвезька крона,2026-08-24 18:28:24.698488,2026-08-24
21,22,SAR,25.08.2026,682,11.906600,None,Саудівський ріял,2026-08-24 18:28:24.698501,2026-08-24
22,23,SGD,25.08.2026,702,35.195500,None,Сінгапурський долар,2026-08-24 18:28:24.698516,2026-08-24
23,24,VND,25.08.2026,704,0.001709,None,Донг,2026-08-24 18:28:24.698530,2026-08-24
24,25,ZAR,25.08.2026,710,2.795000,None,Ренд,2026-08-24 18:28:24.698544,2026-08-24
25,26,SEK,25.08.2026,752,4.707200,None,Шведська крона,2026-08-24 18:28:24.698559,2026-08-24
26,27,CHF,25.08.2026,756,55.738100,None,Швейцарський франк,2026-08-24 18:28:24.698591,2026-08-24
27,28,THB,25.08.2026,764,1.368050,None,Бат,2026-08-24 18:28:24.698608,2026-08-24
28,29,AED,25.08.2026,784,12.171600,None,Дирхам ОАЕ,2026-08-24 18:28:24.698622,2026-08-24
29,30,TND,25.08.2026,788,15.388800,None,Туніський динар,2026-08-24 18:28:24.698637,2026-08-24
30,31,EGP,25.08.2026,818,0.879700,None,Єгипетський фунт,2026-08-24 18:28:24.698650,2026-08-24
31,32,GBP,25.08.2026,826,60.974200,None,Фунт стерлінгів,2026-08-24 18:28:24.698664,2026-08-24
32,33,USD,25.08.2026,840,44.706400,N,Долар США,2026-08-24 18:28:24.698679,2026-08-24
33,34,RSD,25.08.2026,941,0.444550,None,Сербський динар,2026-08-24 18:28:24.698693,2026-08-24
34,35,AZN,25.08.2026,944,26.299400,None,Азербайджанський манат,2026-08-24 18:28:24.698707,2026-08-24
35,36,RON,25.08.2026,946,9.934300,None,Румунський лей,2026-08-24 18:28:24.698721,2026-08-24
36,37,TRY,25.08.2026,949,0.929800,None,Турецька ліра,2026-08-24 18:28:24.698744,2026-08-24
37,38,XDR,25.08.2026,960,61.364100,None,СПЗ (спеціальні права запозичення),2026-08-24 18:28:24.698761,2026-08-24
38,39,EUR,25.08.2026,978,52.159400,None,Євро,2026-08-24 18:28:24.698777,2026-08-24
39,40,GEL,25.08.2026,981,17.130500,None,Ларі,2026-08-24 18:28:24.698792,2026-08-24
40,41,PLN,25.08.2026,985,12.105900,None,Злотий,2026-08-24 18:28:24.698806,2026-08-24
41,42,XAU,25.08.2026,959,208220.860000,None,Золото,2026-08-24 18:28:24.698822,2026-08-24
42,43,XAG,25.08.2026,961,3096.370000,None,Срібло,2026-08-24 18:28:24.698837,2026-08-24
43,44,XPT,25.08.2026,962,84163.820000,None,Платина,2026-08-24 18:28:24.698854,2026-08-24
44,45,XPD,25.08.2026,964,60381.490000,None,Паладій,2026-08-24 18:28:24.698868,2026-08-24

In [13]:
new_row = {
    "currency_key": -1,
    "currency_code": "N/A",
    "currency_name": "Unknown",
    "r030": -1
}
dim.loc[len(dim)] = new_row
dim

/tmp/ipykernel_397/51669522.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dim.loc[len(dim)] = new_row

,currency_key,currency_code,exchangedate,r030,rate,special,currency_name,ingested_at,business_date
0,1,DZD,25.08.2026,12,0.336150,None,Алжирський динар,2026-08-24 18:28:24.698111,2026-08-24
1,2,AUD,25.08.2026,36,32.032100,None,Австралійський долар,2026-08-24 18:28:24.698141,2026-08-24
2,3,BDT,25.08.2026,50,0.364600,None,Така,2026-08-24 18:28:24.698161,2026-08-24
3,4,CAD,25.08.2026,124,32.290200,None,Канадський долар,2026-08-24 18:28:24.698178,2026-08-24
4,5,CNY,25.08.2026,156,6.649400,None,Юань Женьміньбі,2026-08-24 18:28:24.698193,2026-08-24
5,6,CZK,25.08.2026,203,2.164300,None,Чеська крона,2026-08-24 18:28:24.698210,2026-08-24
6,7,DKK,25.08.2026,208,6.977200,None,Данська крона,2026-08-24 18:28:24.698227,2026-08-24
7,8,HKD,25.08.2026,344,5.704700,None,Гонконгівський долар,2026-08-24 18:28:24.698249,2026-08-24
8,9,HUF,25.08.2026,348,0.143956,None,Форинт,2026-08-24 18:28:24.698268,2026-08-24
9,10,INR,25.08.2026,356,0.466920,None,Індійська рупія,2026-08-24 18:28:24.698283,2026-08-24
10,11,IDR,25.08.2026,360,0.002523,None,Рупія,2026-08-24 18:28:24.698299,2026-08-24
11,12,ILS,25.08.2026,376,14.949000,None,Новий ізраїльський шекель,2026-08-24 18:28:24.698317,2026-08-24
12,13,JPY,25.08.2026,392,0.281050,None,Єна,2026-08-24 18:28:24.698334,2026-08-24
13,14,KZT,25.08.2026,398,0.097790,None,Теньге,2026-08-24 18:28:24.698352,2026-08-24
14,15,KRW,25.08.2026,410,0.032310,None,Вона,2026-08-24 18:28:24.698369,2026-08-24
15,16,LBP,25.08.2026,422,0.000499,None,Ліванський фунт,2026-08-24 18:28:24.698402,2026-08-24
16,17,MYR,25.08.2026,458,11.058100,None,Малайзійський ринггіт,2026-08-24 18:28:24.698420,2026-08-24
17,18,MXN,25.08.2026,484,2.641000,None,Мексиканське песо,2026-08-24 18:28:24.698442,2026-08-24
18,19,MDL,25.08.2026,498,2.603000,None,Молдовський лей,2026-08-24 18:28:24.698457,2026-08-24
19,20,NZD,25.08.2026,554,26.661600,None,Новозеландський долар,2026-08-24 18:28:24.698473,2026-08-24
20,21,NOK,25.08.2026,578,4.801000,None,Норвезька крона,2026-08-24 18:28:24.698488,2026-08-24
21,22,SAR,25.08.2026,682,11.906600,None,Саудівський ріял,2026-08-24 18:28:24.698501,2026-08-24
22,23,SGD,25.08.2026,702,35.195500,None,Сінгапурський долар,2026-08-24 18:28:24.698516,2026-08-24
23,24,VND,25.08.2026,704,0.001709,None,Донг,2026-08-24 18:28:24.698530,2026-08-24
24,25,ZAR,25.08.2026,710,2.795000,None,Ренд,2026-08-24 18:28:24.698544,2026-08-24
25,26,SEK,25.08.2026,752,4.707200,None,Шведська крона,2026-08-24 18:28:24.698559,2026-08-24
26,27,CHF,25.08.2026,756,55.738100,None,Швейцарський франк,2026-08-24 18:28:24.698591,2026-08-24
27,28,THB,25.08.2026,764,1.368050,None,Бат,2026-08-24 18:28:24.698608,2026-08-24
28,29,AED,25.08.2026,784,12.171600,None,Дирхам ОАЕ,2026-08-24 18:28:24.698622,2026-08-24
29,30,TND,25.08.2026,788,15.388800,None,Туніський динар,2026-08-24 18:28:24.698637,2026-08-24
30,31,EGP,25.08.2026,818,0.879700,None,Єгипетський фунт,2026-08-24 18:28:24.698650,2026-08-24
31,32,GBP,25.08.2026,826,60.974200,None,Фунт стерлінгів,2026-08-24 18:28:24.698664,2026-08-24
32,33,USD,25.08.2026,840,44.706400,N,Долар США,2026-08-24 18:28:24.698679,2026-08-24
33,34,RSD,25.08.2026,941,0.444550,None,Сербський динар,2026-08-24 18:28:24.698693,2026-08-24
34,35,AZN,25.08.2026,944,26.299400,None,Азербайджанський манат,2026-08-24 18:28:24.698707,2026-08-24
35,36,RON,25.08.2026,946,9.934300,None,Румунський лей,2026-08-24 18:28:24.698721,2026-08-24
36,37,TRY,25.08.2026,949,0.929800,None,Турецька ліра,2026-08-24 18:28:24.698744,2026-08-24
37,38,XDR,25.08.2026,960,61.364100,None,СПЗ (спеціальні права запозичення),2026-08-24 18:28:24.698761,2026-08-24
38,39,EUR,25.08.2026,978,52.159400,None,Євро,2026-08-24 18:28:24.698777,2026-08-24
39,40,GEL,25.08.2026,981,17.130500,None,Ларі,2026-08-24 18:28:24.698792,2026-08-24
40,41,PLN,25.08.2026,985,12.105900,None,Злотий,2026-08-24 18:28:24.698806,2026-08-24
41,42,XAU,25.08.2026,959,208220.860000,None,Золото,2026-08-24 18:28:24.698822,2026-08-24
42,43,XAG,25.08.2026,961,3096.370000,None,Срібло,2026-08-24 18:28:24.698837,2026-08-24
43,44,XPT,25.08.2026,962,84163.820000,None,Платина,2026-08-24 18:28:24.698854,2026-08-24
44,45,XPD,25.08.2026,964,60381.490000,None,Паладій,2026-08-24 18:28:24.698868,2026-08-24
45,-1,N/A,NaN,-1,NaN,NaN,Unknown,NaT,NaT

In [21]:
dim_currency = f"{PROJECT_ID}.nbu_dwh.dim_currency"

dim_to_load = dim[
    ["currency_key", "currency_code", "currency_name", "r030"]
]

schema = [
    bigquery.SchemaField("currency_key", "INT64"),
    bigquery.SchemaField("currency_code", "STRING"),
    bigquery.SchemaField("currency_name", "STRING"),
    bigquery.SchemaField("r030", "INT64"),
]

cfg = bigquery.LoadJobConfig(schema=schema,
                              write_disposition="WRITE_TRUNCATE")


client.load_table_from_dataframe(dim_to_load, dim_currency, job_config=cfg).result()

/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=datalab-504011, location=EU, id=afab4617-6042-4c70-853e-e94e516bcd00>

In [27]:
dim_currency_bq = f"""
SELECT *
FROM `{PROJECT_ID}.nbu_dwh.dim_currency`
"""

dim_currency_data = client.query(dim_currency_bq).to_dataframe()

/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [54]:
# Завдання 3.8. Перевірте трьома рядками й виведіть результат:
dim_currency_data["currency_code"].is_unique
dim_currency_data["currency_key"].isin([-1]).any()
len(dim_currency_data) == parsed["cc"].nunique() + 1

True